# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &environment
  docker:
    - image: circleci/node:13.8.0

commands:
  print_pipeline_id:
    description: "Show me the workflowID"
    steps:
        - run: echo $CIRCLE_WORKFLOW_ID

jobs:

  use_command:
    <<: *environment
    steps:
     - print_pipeline_id


  save_hello_world_ouput:
    <<: *environment
    steps:
      - run: echo "Hello Output !" > /tmp/out1.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - out1.txt
  error_job:
    <<: *environment
    steps:
      - run:
          echo CALL
          return 1
      - run:
          echo FAILED!
          when: on_error
      - run:
          echo SUCCSESS!
          when: on_success


  print_output:
    <<: *environment
    steps:
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/out1.txt




  printhello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello "
  printworld:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello "
  print_var:
    docker:
      - image: cimg/base:2020.01
    steps:
       - checkout
       - run:
           name: "echo an env var that is part of our project"
           command: |
             echo $MY_ENV_VAR

workflows:
  # Name the workflow "welcome"
  holms-test:
    #my jobs
    jobs:
      - error_job
    #  - use_command
    #  - save_hello_world_ouput
    #  - print_output:
    #      requires:
     #       - save_hello_world_ouput
     # - printhello
     # - printworld:
     #     requires:
     #       - printhello

